// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdeQlQ3veLAdSSdDHhxbNOfucfGC63XpM',
    appId: '1:793366152220:web:0f7282819c924abbf04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    authDomain: 'blog-app-3-p.firebaseapp.com',
    storageBucket: 'blog-app-3-p.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FCCcqpkUm_REPyDTns4zCyxi0Ey9QI8',
    appId: '1:793366152220:android:0ebe3a54ba82fe3af04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    storageBucket: 'blog-app-3-p.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Jc0vX0dt2OJxrgvN8-BfiHQeJq7Fe_o',
    appId: '1:793366152220:ios:5949c2e0e7492b73f04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    storageBucket: 'blog-app-3-p.appspot.com',
    androidClientId: '793366152220-bpgho4selu61omq1qshk6k5p8tc9jvoo.apps.googleusercontent.com',
    iosClientId: '793366152220-a6ph1e1n8or26s9m25je5q1g17rl9gva.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Jc0vX0dt2OJxrgvN8-BfiHQeJq7Fe_o',
    appId: '1:793366152220:ios:5949c2e0e7492b73f04bd9',
    messagingSenderId: '793366152220',
    projectId: 'blog-app-3-p',
    storageBucket: 'blog-app-3-p.appspot.com',
    androidClientId: '793366152220-bpgho4selu61omq1qshk6k5p8tc9jvoo.apps.googleusercontent.com',
    iosClientId: '793366152220-a6ph1e1n8or26s9m25je5q1g17rl9gva.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
